FROM python:2.7

WORKDIR /home
ENV http_proxy $proxy
ENV https_proxy $proxy
ENV DNS $dns
ENV TARGET $target
ENV OUTPUT $output
ENV VT_KEY $vt_key

RUN mkdir -p $OUTPUT

RUN if [ -n "$DNS" ]; \
    then echo "nameserver $DNS" > /etc/resolv.conf;\
    fi;\
    apt-get update && \
    apt-get install -y git python-dnspython && \
	  rm -rf /var/lib/apt/lists/*

RUN if [ -n "$DNS" ]; \
    then echo "nameserver $DNS" > /etc/resolv.conf;\
    fi;\
    git clone https://github.com/guelfoweb/knock.git /home/knock

WORKDIR /home/knock

RUN if [ -n "$DNS" ]; \
    then echo "nameserver $DNS" > /etc/resolv.conf;\
    fi;\
    python setup.py install

RUN if [ -n "$VT_KEY" ]; \
    then sed -i ".orig" 's/""/"$VT_KEY"/g' knockpy/config.json;\
    fi

WORKDIR $OUTPUT

ENTRYPOINT knockpy -j $TARGET
