FROM python:3.6

ENV http_proxy $proxy
ENV https_proxy $proxy
ENV DNS $dns
ENV TARGET $target
ENV OUTPUT $output/ctfr.txt
ENV INFILE  $infile

RUN if [ -n "$DNS" ]; \
    then echo "nameserver $dns" >> /etc/resolv.conf; fi;\
 	apt-get update && apt-get install -y --no-install-recommends \
            python-dev \
			git 


RUN if [ -n "$DNS" ]; \
    then echo "nameserver $dns" >> /etc/resolv.conf; fi;\
	git clone https://github.com/UnaPibaGeek/ctfr.git ctfr


WORKDIR /ctfr

RUN if [ -n "$DNS" ]; \
    then echo "nameserver $dns" >> /etc/resolv.conf; fi;\
 	pip3 install -r requirements.txt

RUN mkdir -p $output

ENTRYPOINT python ctfr.py -d $$TARGET -o $$OUTPUT
