FROM python:2.7

WORKDIR /root

ENV http_proxy $proxy
ENV https_proxy $proxy
ENV DNS $dns
ENV TARGET $target
ENV OUTPUT $output

RUN if [ -n "$$DNS" ];\
    then echo "nameserver $dns" >> /etc/resolv.conf;\
    fi;\
	apt install -y git ;\
    pip install dnspython;

RUN if [ -n "$$DNS" ];\
    then echo "nameserver $dns" >> /etc/resolv.conf;\
    fi;\
    git clone https://github.com/TheRook/subbrute.git subbrute

RUN mkdir -p $output

WORKDIR /root/subbrute

ENTRYPOINT ./subbrute.py -o $output/subbrute.txt $target
