FROM kalilinux/kali-linux-docker

WORKDIR /home
ENV http_proxy $proxy
ENV https_proxy $proxy
ENV DNS $dns
ENV TARGET $target
ENV OUTPUT $output

RUN if [ -n "$$DNS" ];\
    then echo "nameserver $$DNS" > /etc/resolv.conf;\
    fi;\ 
    apt update && apt upgrade && apt install -y python3.4 git

RUN if [ -n "$$DNS" ];\
    then echo "nameserver $$DNS" > /etc/resolv.conf;\
    fi;\
    pip3 install dnspython; exit 0

RUN if [ -n "$$DNS" ];\
    then echo "nameserver $$DNS" > /etc/resolv.conf;\
    fi;\
    git clone https://github.com/TheRook/subbrute.git subbrute

RUN mkdir -p $$OUTPUT

WORKDIR subbrute

ENTRYPOINT ./subbrute.py -o $$OUTPUT/subbrute.txt $$TARGET
