FROM python:3.4

WORKDIR /home
ENV http_proxy $proxy
ENV https_proxy $proxy
ENV DNS $dns

RUN mkdir -p $output

RUN if [ -n "$$DNS" ]; \
    then echo "nameserver $dns" >> /etc/resolv.conf;\
    fi;\
    apt-get install git

RUN if [ -n "$$DNS" ];\
    then echo "nameserver $dns" >> /etc/resolv.conf;\
    fi;\
    git clone https://github.com/aboul3la/Sublist3r.git /home/sublist

WORKDIR /home/sublist

RUN if [ -n "$$DNS" ]; \
    then echo "nameserver $dns" >> /etc/resolv.conf;\
    fi;\
    pip3 install -r requirements.txt

ENV TARGET $target
ENV OUTPUT $output

ENTRYPOINT python3 sublist3r.py --domain $target -o $output/sublist3r.txt
