FROM golang:1.11.4-alpine3.7 AS build-env

ENV http_proxy $proxy
ENV https_proxy $proxy

RUN apk add --no-cache --upgrade git openssh-client ca-certificates
RUN go get -u github.com/golang/dep/cmd/dep
WORKDIR /go/src/app

# Install
RUN go get -u github.com/subfinder/subfinder

RUN mkdir -p $output

ENTRYPOINT subfinder -d "$target" -o $output/subfinder.json -oJ 
