FROM python:3.6

ENV http_proxy $proxy
ENV https_proxy $proxy

RUN if [ -n "$dns" ]; \
    then echo "nameserver $dns" >> /etc/resolv.conf; fi;\
 	apt-get update && apt-get install -y --no-install-recommends \
            python-dev \
			git 


RUN if [ -n "$dns" ]; \
    then echo "nameserver $dns" >> /etc/resolv.conf; fi;\
 	git clone https://github.com/chris408/ct-exposer.git ctexposure


WORKDIR /ctexposure

RUN if [ -n "$dns" ]; \
    then echo "nameserver $dns" >> /etc/resolv.conf; fi;\
 	pip3 install -r requirements.txt

ENV INFILE  $infile

RUN mkdir -p $output

ENTRYPOINT python ct-exposer.py -d "$target" -m -u > $output/ctexposure.txt
