FROM python:3.6

ENV http_proxy $proxy
ENV https_proxy $proxy

RUN if [ -n $dns ]; \
    then echo "nameserver $dns" >> /etc/resolv.conf; fi;\
 	apt-get update && apt-get install -y python-dev git ca-certificates

ADD certs/ /usr/local/share/ca-certificates/
RUN update-ca-certificates

RUN if [ -n $dns ]; \
    then echo "nameserver $dns" >> /etc/resolv.conf; fi;\
 	git clone https://github.com/chris408/ct-exposer.git ctexposure


WORKDIR /ctexposure

RUN if [ -n $dns ]; \
    then echo "nameserver $dns" >> /etc/resolv.conf; fi;\
 	pip3 install --trusted-host pypi.python.org  --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements.txt

ENV INFILE  $infile

RUN mkdir -p $output

ENTRYPOINT python ct-exposer.py -d "$target" -m -u > $output/ctexposure.txt
