FROM python:2.7

WORKDIR /root

ENV http_proxy $proxy
ENV https_proxy $proxy

RUN if [ -n $dns ];\
    then echo "nameserver $dns" >> /etc/resolv.conf;\
    fi;\
	apt install -y git ca-certificates;\
    pip install --trusted-host pypi.org dnspython;

ADD certs/ /usr/local/share/ca-certificates/
RUN update-ca-certificates

RUN if [ -n $dns ];\
    then echo "nameserver $dns" >> /etc/resolv.conf;\
    fi;\
    git clone https://github.com/TheRook/subbrute.git subbrute

RUN mkdir -p $output

WORKDIR /root/subbrute

ENTRYPOINT ./subbrute.py -o $output/subbrute.txt -r resolvers.txt -p -v $target
