FROM python:3.7-slim

ENV http_proxy $proxy
ENV https_proxy $proxy

RUN if [ -n $dns ]; \
    then echo "nameserver $dns" >> /etc/resolv.conf; fi;\
 	apt-get update && apt-get install -y --no-install-recommends \
            build-essential \
            libssl-dev \
            libffi-dev \
            python-dev \
			git \
        && rm -rf /var/lib/apt/lists/*


RUN if [ -n $dns ]; \
    then echo "nameserver $dns" >> /etc/resolv.conf; fi;\
 	git clone https://github.com/jonluca/Anubis.git anubis


WORKDIR /anubis

RUN if [ -n $dns ]; \
    then echo "nameserver $dns" >> /etc/resolv.conf; fi;\
 	pip3 install -r requirements.txt; \
	pip3 install .

RUN mkdir -p $output

ENTRYPOINT anubis -t "$target" -o $output/anubis.txt -i
