FROM ubuntu:latest

ENV http_proxy $proxy
ENV https_proxy $proxy

RUN if [ -n $dns ]; \
    then echo "nameserver $dns" >> /etc/resolv.conf;\
    fi;\
    apt-get update \
    && apt-get install -y wget git python python-pip chromium-browser xvfb firefox phantomjs ca-certificates

ADD certs/ /usr/local/share/ca-certificates/
RUN update-ca-certificates


RUN if [ -n $dns ]; \
    then echo "nameserver $dns" >> /etc/resolv.conf;\
    fi;\
    git clone https://github.com/maaaaz/webscreenshot.git webscreenshot 

WORKDIR webscreenshot

RUN if [ -n $dns ]; \
    then echo "nameserver $dns" >> /etc/resolv.conf;\
    fi;\
    pip install -r requirements.txt

RUN if [ -n $dns ]; \
    then echo "nameserver $dns" >> /etc/resolv.conf;\
    fi;\
    pip install -r requirements.txt


ENV OUTPUT $output/webscreenshot

RUN mkdir -p $OUTPUT 

ENTRYPOINT python webscreenshot.py -i $infile -o $output/webscreenshot -r $tool --no-xserver
